title: David Kraemer
description: Personal Site
author: David Kraemer 
logo: /assets/profile.jpg
github: https://github.com/ashutosh2k12
about: Undergraduate student &mdash; Lead developer 

baseurl: ""
url: ""

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
