title: David Kraemer
description: Personal Site
author: David Kraemer 
logo: /assets/profile.jpg
github: https://github.com/kraemerd17
about: Graduate student <br/> Stony Brook University
baseurl: ""
url: ""

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#david\_kraemer
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, rouge]
highlighter: rouge