#!/usr/bin/env python3

import subprocess
import sys
import os

filename = os.path.basename(sys.argv[1])
file = os.path.splitext(filename)[0]

com = "convert -density 300 {} - quality 90 {}.png".format(sys.argv[1], file)

subprocess.call(com, shell=True)
